server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: gateway
    version: project.version@
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowed-origin-patterns:
              -  "*"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: restapi
          uri: lb://restapi
          predicates:
            - Path=/restapi/**
          filters:
            - RewritePath=/restapi/?(?<segment>.*), /$\{segment}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    instance-id: gateway
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5