server:
  port: 8761

eureka:
  instance:
    hostname: eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 5000
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: project.name@
    version: project.version@